In [24]:
import polars as pl
from pathlib import Path

DATA_DIR = Path.cwd().parent / "data" 


df = pl.read_csv(
    str(DATA_DIR / "data-raw" / "household_power_consumption.txt"), 
    separator=";",
    null_values="?"
)

df

shape: (2_075_259, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Date      ┆ Time     ┆ Global_ac ┆ Global_re ┆ … ┆ Global_in ┆ Sub_meter ┆ Sub_meter ┆ Sub_meter │
│ ---       ┆ ---      ┆ tive_powe ┆ active_po ┆   ┆ tensity   ┆ ing_1     ┆ ing_2     ┆ ing_3     │
│ str       ┆ str      ┆ r         ┆ wer       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 16/12/200 ┆ 17:24:00 ┆ 4.216     ┆ 0.418     ┆ … ┆ 18.4      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:25:00 ┆ 5.36      ┆ 0.436     ┆ … ┆ 23.0      ┆ 0.0       ┆ 1.0       ┆ 16.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:26:00 ┆ 5.374     ┆ 0.498     ┆ … ┆ 23.0      ┆ 0.0       ┆ 2.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:27:00 ┆ 5.388     ┆ 0.502     ┆ … ┆ 23.0      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:28:00 ┆ 3.666     ┆ 0.528     ┆ … ┆ 15.8      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 26/11/201 ┆ 20:58:00 ┆ 0.946     ┆ 0.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 20:59:00 ┆ 0.944     ┆ 0.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:00:00 ┆ 0.938     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:01:00 ┆ 0.934     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:02:00 ┆ 0.932     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
df = df.rename(str.lower)
df

shape: (2_075_259, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ date      ┆ time     ┆ global_ac ┆ global_re ┆ … ┆ global_in ┆ sub_meter ┆ sub_meter ┆ sub_meter │
│ ---       ┆ ---      ┆ tive_powe ┆ active_po ┆   ┆ tensity   ┆ ing_1     ┆ ing_2     ┆ ing_3     │
│ str       ┆ str      ┆ r         ┆ wer       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│           ┆          ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 16/12/200 ┆ 17:24:00 ┆ 4.216     ┆ 0.418     ┆ … ┆ 18.4      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:25:00 ┆ 5.36      ┆ 0.436     ┆ … ┆ 23.0      ┆ 0.0       ┆ 1.0       ┆ 16.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:26:00 ┆ 5.374     ┆ 0.498     ┆ … ┆ 23.0      ┆ 0.0       ┆ 2.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:27:00 ┆ 5.388     ┆ 0.502     ┆ … ┆ 23.0      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 16/12/200 ┆ 17:28:00 ┆ 3.666     ┆ 0.528     ┆ … ┆ 15.8      ┆ 0.0       ┆ 1.0       ┆ 17.0      │
│ 6         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 26/11/201 ┆ 20:58:00 ┆ 0.946     ┆ 0.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 20:59:00 ┆ 0.944     ┆ 0.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:00:00 ┆ 0.938     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:01:00 ┆ 0.934     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 26/11/201 ┆ 21:02:00 ┆ 0.932     ┆ 0.0       ┆ … ┆ 3.8       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ 0         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Uno de los problemas es que tenemos una columna en un formato que no es fecha, y la hora tambien esta en string. Lo que podemos hacer de una vez es combinarlos en el tipo de dato datetime para polars

In [26]:
print(df["date"].dtype)

String

In [27]:
df = df.with_columns(
    (pl.col("date") + " " + pl.col("time"))
    .str.to_datetime("%d/%m/%Y %H:%M:%S")
    .alias("datetime")
)
df = df.drop("date", "time")
df = df.select("datetime", *df.columns[:len(df.columns)-1])
df

shape: (2_075_259, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬────────────┬───────────┬───────────┐
│ datetime   ┆ global_act ┆ global_rea ┆ voltage ┆ global_int ┆ sub_meteri ┆ sub_meter ┆ sub_meter │
│ ---        ┆ ive_power  ┆ ctive_powe ┆ ---     ┆ ensity     ┆ ng_1       ┆ ing_2     ┆ ing_3     │
│ datetime[μ ┆ ---        ┆ r          ┆ f64     ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ s]         ┆ f64        ┆ ---        ┆         ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
│            ┆            ┆ f64        ┆         ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪═════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 2006-12-16 ┆ 4.216      ┆ 0.418      ┆ 234.84  ┆ 18.4       ┆ 0.0        ┆ 1.0       ┆ 17.0      │
│ 17:24:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-16 ┆ 5.36       ┆ 0.436      ┆ 233.63  ┆ 23.0       ┆ 0.0        ┆ 1.0       ┆ 16.0      │
│ 17:25:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-16 ┆ 5.374      ┆ 0.498      ┆ 233.29  ┆ 23.0       ┆ 0.0        ┆ 2.0       ┆ 17.0      │
│ 17:26:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-16 ┆ 5.388      ┆ 0.502      ┆ 233.74  ┆ 23.0       ┆ 0.0        ┆ 1.0       ┆ 17.0      │
│ 17:27:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-16 ┆ 3.666      ┆ 0.528      ┆ 235.68  ┆ 15.8       ┆ 0.0        ┆ 1.0       ┆ 17.0      │
│ 17:28:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …       ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2010-11-26 ┆ 0.946      ┆ 0.0        ┆ 240.43  ┆ 4.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ 20:58:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-11-26 ┆ 0.944      ┆ 0.0        ┆ 240.0   ┆ 4.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ 20:59:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-11-26 ┆ 0.938      ┆ 0.0        ┆ 239.82  ┆ 3.8        ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ 21:00:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-11-26 ┆ 0.934      ┆ 0.0        ┆ 239.7   ┆ 3.8        ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ 21:01:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-11-26 ┆ 0.932      ┆ 0.0        ┆ 239.55  ┆ 3.8        ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ 21:02:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
└────────────┴────────────┴────────────┴─────────┴────────────┴────────────┴───────────┴───────────┘

In [28]:
df.filter(pl.col("voltage").is_null())

shape: (25_979, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬────────────┬───────────┬───────────┐
│ datetime   ┆ global_act ┆ global_rea ┆ voltage ┆ global_int ┆ sub_meteri ┆ sub_meter ┆ sub_meter │
│ ---        ┆ ive_power  ┆ ctive_powe ┆ ---     ┆ ensity     ┆ ng_1       ┆ ing_2     ┆ ing_3     │
│ datetime[μ ┆ ---        ┆ r          ┆ f64     ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ s]         ┆ f64        ┆ ---        ┆         ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
│            ┆            ┆ f64        ┆         ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪════════════╪═════════╪════════════╪════════════╪═══════════╪═══════════╡
│ 2006-12-21 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 11:23:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-21 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 11:24:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-30 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 10:08:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2006-12-30 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 10:09:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2007-01-14 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 18:36:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …       ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2010-09-28 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 19:09:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-09-28 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 19:10:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-09-28 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 19:11:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-09-28 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 19:12:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
│ 2010-10-24 ┆ null       ┆ null       ┆ null    ┆ null       ┆ null       ┆ null      ┆ null      │
│ 15:35:00   ┆            ┆            ┆         ┆            ┆            ┆           ┆           │
└────────────┴────────────┴────────────┴─────────┴────────────┴────────────┴───────────┴───────────┘

Notamos que todas las columnas con valores nulos en algun atributo de hecho tiene nulos en todos los demas, puede que los valores donde falten datos sea utiles
# importante
tal vez lo mejor sea dejarlos porque puede reflejar fenomenos

In [29]:
df = df.drop_nulls()
df.null_count()

shape: (1, 8)
┌──────────┬────────────┬────────────┬─────────┬────────────┬────────────┬────────────┬────────────┐
│ datetime ┆ global_act ┆ global_rea ┆ voltage ┆ global_int ┆ sub_meteri ┆ sub_meteri ┆ sub_meteri │
│ ---      ┆ ive_power  ┆ ctive_powe ┆ ---     ┆ ensity     ┆ ng_1       ┆ ng_2       ┆ ng_3       │
│ u32      ┆ ---        ┆ r          ┆ u32     ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│          ┆ u32        ┆ ---        ┆         ┆ u32        ┆ u32        ┆ u32        ┆ u32        │
│          ┆            ┆ u32        ┆         ┆            ┆            ┆            ┆            │
╞══════════╪════════════╪════════════╪═════════╪════════════╪════════════╪════════════╪════════════╡
│ 0        ┆ 0          ┆ 0          ┆ 0       ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└──────────┴────────────┴────────────┴─────────┴────────────┴────────────┴────────────┴────────────┘

In [30]:
df.write_csv(DATA_DIR / "data-processed" / "cleaned_data.csv")